# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            GNA
tagline:          'The GNA Project'
description:      'The Geographic Network Analysis Project'
url:              http://joaoponceleao.github.io/GNA/

author:
  name:           'João Ponce de Leão'
  url:            https://github.com/joaoponceleao

paginate:         5
